tools:
  - class_name: "verl.tools.agent_distill_tool.AgentDistillTool"
    config: 
      type: native
    tool_schema:
      type: "function"
      function:
        name: "exec_python_code_block"
        description: "A tool for execute the code block of python"
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The code to the be executed"
            scope:
              type: "object"
              description: "The scope of the code"
          required: ["code", "scope"]

  - class_name: "verl.tools.search_tool.SearchTool"
    config: 
      type: native
      retrieval_service_url: "anonymous"
      topk: 10
      num_workers: 10
      rate_limit: 10
    tool_schema:
      type: "function"
      function:
        name: "web_search"
        description: "A tool for execute the web search"
        parameters:
          type: "object"
          properties:
            query:
              type: "string"
              description: "The query to the be executed"
          required: ["query"]
